Criando Entidades
daianebellon/chaves-pix-api pull request #1
Opened 2021-08-04 21:42 UTC by daianebellon

2021-08-05 16:53 UTC, rcpadilha requested changes

2021-08-05 16:53 UTC, rcpadilha commented on src/main/java/com/daiane/pix/gateway/database/entity/chavepix/ChavePix.java
> +    private LocalDate dataCadastro = LocalDate.now();
Não cria com valor default aqui, deixa pra definir o valor no use case.

2021-08-05 16:53 UTC, rcpadilha commented on src/main/java/com/daiane/pix/gateway/database/entity/codigovalidacao/CodigoValidacao.java
> +public class CodigoValidacao {
Faltou configurar a chave primária.

2021-08-05 16:53 UTC, rcpadilha commented on src/main/java/com/daiane/pix/gateway/database/entity/codigovalidacao/CodigoValidacao.java
> +    private int codigoOtp ;
Usa Integer.

2021-08-05 22:19 UTC, daianebellon commented on src/main/java/com/daiane/pix/gateway/database/entity/chavepix/ChavePix.java
> +    private LocalDate dataCadastro = LocalDate.now();
Ok! arrumado!

2021-08-05 22:20 UTC, daianebellon commented on src/main/java/com/daiane/pix/gateway/database/entity/codigovalidacao/CodigoValidacao.java
> +public class CodigoValidacao {
No BD ele diz que é uma chave composta, seria isso mesmo?

2021-08-05 22:20 UTC, daianebellon commented on src/main/java/com/daiane/pix/gateway/database/entity/codigovalidacao/CodigoValidacao.java
> +    private int codigoOtp ;
Ok! arrumado!

2021-08-06 11:46 UTC, rcpadilha commented on src/main/java/com/daiane/pix/gateway/database/entity/codigovalidacao/CodigoValidacao.java
> +public class CodigoValidacao {
Isso mesmo.

2021-08-06 21:16 UTC, merged